### PR TITLE
Added dotenv configuration + fixed some SonarQube issues

### LINKED ISSUE #1: Handle API keys securely with dotenv

### PR DESCRIPTION
**Pull request by rainer-schreiber**

### CODE REVIEW

File: src/main/kotlin/ai/smartcodingtool/domain/LlmDirective.kt [hunk 1]
```diff
@@ -11,5 +11,7 @@ data class LlmDirective(
     fun getSystemPrompt(): String {
          // aspects
         // what to generate
+
```
Comment (bluevoidnl) [inline src/main/kotlin/ai/smartcodingtool/domain/LlmDirective.kt:14]: Sorry about that ! : D
